apiVersion: v1
kind: Service
metadata:
  name: insights-app-svc
  namespace: insights
  labels:
    app.kubernetes.io/name: insights-app
spec:
  type: ClusterIP
  selector:
    app: insights-app
  ports:
    - port: 3000
      targetPort: 3000
