# Source: infra/ingress.yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: insights
  labels:
    name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  tls:
    - hosts:
        - insights.production.lfx.dev
        - insights.linuxfoundation.org
      secretName: letsencrypt-production
  rules:
    - host: insights.production.lfx.dev
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: insights-app-svc
                port:
                  number: 3000
    - host: insights.linuxfoundation.org
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: insights-app-svc
                port:
                  number: 3000
---
# Source: infra/namespace.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: insights
---
# Source: infra/redis.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dpl
  namespace: insights
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        name: pg-insights-redis
      containers:
        - name: redis
          image: crowddotdev/redis:1668671743.d99338c4
          command: ['redis-server']
          args:
            ['/redis.conf', '--requirepass', 'V434DbYua628UmgD8BHxiCuMNXxXu4kD']
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: insights
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
# Source: insights-app.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insights-app-dpl
  namespace: insights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insights-app
  template:
    metadata:
      labels:
        app: insights-app
    spec:
      nodeSelector:
        name: pg-insights
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "insights"
          effect: "NoSchedule"
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: frontend
          image: sjc.ocir.io/axbydjxa5zuh/insights-app:2
          envFrom:
            - configMapRef:
                name: insights-config-map
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              port: 3000
              path: /api/health/live
          livenessProbe:
            httpGet:
              port: 3000
              path: /api/health/live
---
apiVersion: v1
kind: Service
metadata:
  name: insights-app-svc
  namespace: insights
spec:
  type: ClusterIP
  selector:
    app: insights-app
  ports:
    - port: 3000
      targetPort: 3000
---
# Source: package-downloads-worker.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-downloads-worker-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: package-downloads-worker
  template:
    metadata:
      labels:
        app: package-downloads-worker
    spec:
      nodeSelector:
        name: pg-insights
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: package-downloads-worker
          image: sjc.ocir.io/axbydjxa5zuh/package-downloads-worker:1750147302.2d64686
          workingDir: /usr/insights/app/workers/temporal/package_downloads_worker
          command:
            - pnpm
          args:
            - run
            - start
          envFrom:
            - configMapRef:
                name: insights-config-map
          env:
            - name: KUBE_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
---
# Source: search-volume-worker.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-volume-worker-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-volume-worker
  template:
    metadata:
      labels:
        app: search-volume-worker
    spec:
      nodeSelector:
        name: pg-insights
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: search-volume-worker
          image: sjc.ocir.io/axbydjxa5zuh/insights-search-volume-worker:1752680491.4e4905d
          workingDir: /insights-search-volume-app/workers/temporal/search_volume_worker
          command:
            - pnpm
          args:
            - run
            - start
          envFrom:
            - configMapRef:
                name: insights-config-map
          env:
            - name: KUBE_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
