apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: insights
  labels:
    name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - insights.production.lfx.dev
        - insights.linuxfoundation.org
      secretName: letsencrypt-production
  rules:
    - host: insights.production.lfx.dev
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: insights-app-svc
                port:
                  number: 3000
    - host: insights.linuxfoundation.org
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: insights-app-svc
                port:
                  number: 3000
