---
apiVersion: v1
kind: Namespace
metadata:
  name: oci-secrets-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oci-secrets-operator
  namespace: oci-secrets-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oci-secrets-operator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["secrets.oracle.com"]
    resources: ["secretsyncs", "secretsyncs/status"]
    verbs: ["*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oci-secrets-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oci-secrets-operator
subjects:
  - kind: ServiceAccount
    name: oci-secrets-operator
    namespace: oci-secrets-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-secrets-operator
  namespace: oci-secrets-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oci-secrets-operator
  template:
    metadata:
      labels:
        app: oci-secrets-operator
    spec:
      serviceAccountName: oci-secrets-operator
      containers:
        - name: controller
          image: ghcr.io/oracle/oci-secrets-operator:1.0.0
          args:
            - "--leader-elect=true"
          env:
            - name: WATCH_NAMESPACE
              value: "insights"
            - name: METRICS_BIND_ADDRESS
              value: ":8080"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
