apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - secrets-mapping.yaml
patches:
  - path: patches/ingress.yaml
  - path: patches/secret-mapping.yaml
  - path: patches/deployment-env.yaml
